<?php

use App\Http\Controllers\Tools\AltCheckerController;
use App\Http\Controllers\Tools\AnchorTextAnalyzerController;
use App\Http\Controllers\Tools\BrokenImageFinderController;
use App\Http\Controllers\Tools\ColorPaletteController;
use App\Http\Controllers\Tools\CssVariableScannerController;
use App\Http\Controllers\Tools\DnsLookupController;
use App\Http\Controllers\Tools\FaqExtractorController;
use App\Http\Controllers\Tools\FontDetectorController;
use App\Http\Controllers\Tools\HeadingCheckerController;
use App\Http\Controllers\Tools\LinkCheckerController;
use App\Http\Controllers\Tools\OgPreviewController;
use App\Http\Controllers\Tools\PageWeightController;
use App\Http\Controllers\Tools\RedirectChainController;
use App\Http\Controllers\Tools\SchemaExtractorController;
use App\Http\Controllers\Tools\ScriptAuditController;
use App\Http\Controllers\Tools\SecurityHeadersController;
use App\Http\Controllers\Tools\SeoAnalyzerController;
use App\Http\Controllers\Tools\SitemapDiffController;
use App\Http\Controllers\Tools\TailwindExtractorController;
use App\Http\Controllers\Tools\TechStackDetectorController;
use App\Http\Controllers\Tools\TrackerInventoryController;
use App\Http\Controllers\Tools\TypographySeoCheckerController;
use Illuminate\Support\Facades\Route;

Route::post('/alt-checker', [AltCheckerController::class, 'analyze']);
Route::post('/anchor-text-analyzer', [AnchorTextAnalyzerController::class, 'analyze']);
Route::post('/broken-image-finder', [BrokenImageFinderController::class, 'analyze']);
Route::post('/color-palette', [ColorPaletteController::class, 'analyze']);
Route::post('/css-variable-scanner', [CssVariableScannerController::class, 'analyze']);
Route::post('/dns-lookup', [DnsLookupController::class, 'analyze']);
Route::post('/faq-extractor', [FaqExtractorController::class, 'analyze']);
Route::post('/font-detector', [FontDetectorController::class, 'analyze']);
Route::post('/heading-checker', [HeadingCheckerController::class, 'analyze']);
Route::post('/link-checker', [LinkCheckerController::class, 'analyze']);
Route::post('/link-status', [LinkCheckerController::class, 'status']);
Route::post('/og-preview', [OgPreviewController::class, 'analyze']);
Route::post('/page-weight', [PageWeightController::class, 'analyze']);
Route::post('/redirect-chain', [RedirectChainController::class, 'analyze']);
Route::post('/schema-extractor', [SchemaExtractorController::class, 'analyze']);
Route::post('/script-audit', [ScriptAuditController::class, 'analyze']);
Route::post('/security-headers', [SecurityHeadersController::class, 'analyze']);
Route::post('/seo-analyzer', [SeoAnalyzerController::class, 'analyze']);
Route::post('/sitemap-diff', [SitemapDiffController::class, 'analyze']);
Route::post('/tailwind-extractor', [TailwindExtractorController::class, 'analyze']);
Route::post('/tech-stack-detector', [TechStackDetectorController::class, 'analyze']);
Route::post('/tracker-inventory', [TrackerInventoryController::class, 'analyze']);
Route::post('/typography-seo-checker', [TypographySeoCheckerController::class, 'analyze']);
